name       : compiz-plugins-main
version    : 0.8.16
release    : 1
source     :
    - https://gitlab.com/compiz/compiz-plugins-main/-/archive/v0.8.16/compiz-plugins-main-v0.8.16.tar.bz2 : b639d67543f018dbbb3bea9d2404b157f63c1bed2705de19cf496e24edc29ab4
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Non-default Compiz compositing manager plugins.
description: |
    Non-default Compiz compositing manager plugins.
builddeps  :
    - pkgconfig(atspi-2)
    - pkgconfig(bcop)
    - pkgconfig(pangocairo)
    - pkgconfig(compiz)
    - pkgconfig(glu)
    - libjpeg-turbo-devel
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
