name       : compiz-plugins-main
version    : 0.8.18
release    : 2
source     :
    - https://gitlab.com/compiz/compiz-plugins-main/-/archive/v0.8.18/compiz-plugins-main-v0.8.18.tar.bz2 : 3125ff654b3a422b819d5b5d90406d4efc8fa4c7a66cc4a63efe6597574ad549
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Non-default Compiz compositing manager plugins
description: |
    Non-default Compiz compositing manager plugins.
builddeps  :
    - pkgconfig(atspi-2)
    - pkgconfig(bcop)
    - pkgconfig(compiz)
    - pkgconfig(glu)
    - pkgconfig(libturbojpeg)
    - pkgconfig(pangocairo)
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
